---

- name: ensure instance exists in openstack
  nova_compute:
    state: present
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    auth_url: "{{ os_auth_url }}"
    region_name: "{{ os_region_name }}"
    name: "{{ inventory_hostname }}"
    image_id: "{{ os_image_id }}"
    key_name: "{{ os_key_name }}"
    flavor_id: "{{ flavor_id }}"
    security_groups: default
  register: nova

#
# I'm going to leave some of the debug entries here but commented out
#

#- debug: msg="{{ nova }}"

#- debug: msg="{{ nova.info }}"

#- debug: msg="{{nova.name}}"

- name: add the instance to the in-memory inventory
  add_host: name={{ inventory_hostname }}

# Pause for a while if the vm has just been created
- pause: seconds=30
  when: nova.changed

- set_fact: ansible_ssh_host={{ nova.info.addresses.private[0].addr }}

#- debug: msg="{{ inventory_hostname }} {{ ansible_default_ipv4.address }}"

#- debug: msg="{{ ansible_ssh_host }}"

#- debug: var=hostvars[inventory_hostname]
